language: java

cache:
  directories:
    - $HOME/.m2

before_script:
 - cd quickfix
 
jdk:
  - oraclejdk7
#  - oraclejdk8

env:
  global:
    - MAVEN_OPTS="-Xms2048m -Xmx4096m -XshowSettings -verbose:gc"
    
script: mvn clean
