language: java

cache:
  directories:
    - $HOME/.m2

before_script:
 - cd quickfix
 
jdk:
  - oraclejdk7
#  - oraclejdk8

env:
  global:
    - JAVA_OPTS="-Xms1024m -Xmx1024m -XX:+TieredCompilation"
    - MAVEN_OPTS="-Xms2048m -Xmx2048m -XX:+TieredCompilation"
